update yml file for aws deployment

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -42,6 +42,13 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
 
+      - name: Debug SSH Key Authentication
+        run: |
+          echo "Checking SSH key..."
+          ssh-add -l || echo "No SSH keys loaded"
+          ssh -T ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_INSTANCE_ID }} || echo "SSH connection failed"
+        
+
       - name: Deploy Docker image to EC2
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_INSTANCE_ID }} << 'EOF'
